# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_auto_20160731_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host_user',
            name='user',
        ),
        migrations.AddField(
            model_name='host_user',
            name='username',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
