# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20160731_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_user',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
