# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_host_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='superivsor',
            new_name='supervisor',
        ),
    ]
